apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockstumize-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mockstumize
  template:
    metadata:
      labels:
        app: mockstumize
    spec:
      containers:
        - name: app
          image: nginx:1.25
